file_project/file_download/urls.py
from django.urls import path,re_path
from . import views

app_name = 'file_download'

urlpatterns = [
    re_path(r'^download/(?P<file_path>.*)/$',views.file_response_download,name='file_download'),
]

file_project/file_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('file/',include("file_upload.urls")),
    path('file1/',include("file_download.urls")),
    path('tasks/',include("tasks.urls"))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

file_project/file_upload/urls.py
from django.urls import re_path,path
from . import views

app_name = 'file_upload'

urlpatterns = [
    re_path(r'^upload1/$',views.file_upload,name='file_upload'),
    re_path(r'^upload2/$',views.model_form_upload,name='model_form_upload'),
    re_path(r'^upload3/$',views.ajax_form_upload,name='ajax_form_upload'),
    re_path(r'^ajax_upload/$',views.ajax_upload,name='ajax_upload'),
    # re_path(r'^/$',views.file_list,name='file_list'),
    path('',views.file_list,name='file_list'),
]

file_project/tasks/urls.py
# -*- coding:utf-8 -*-

from django.urls import path, re_path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('create/', views.TaskCreateView.as_view(), name='task_create'),
    path('', views.TaskListView.as_view(), name='task_list'),
    re_path(r'^(?P<pk>\d+)/$', views.TaskDetailView.as_view(), name='task_detail'),
    re_path(r'^(?P<pk>\d+)/update/$', views.TaskUpdateView.as_view(), name='task_update'),
    re_path(r'^(?P<pk>\d+)/delete/$', views.TaskDeleteView.as_view(), name='task_delete'),
]

file_project/file_download/models.py
from django.db import models

# Create your models here.

file_project/file_upload/models.py
from django.db import models
import os
import uuid


# Create your models here.

def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    return os.path.join("files", filename)

class File(models.Model):
    file = models.FileField(upload_to=user_directory_path,null=True)
    upload_method = models.CharField(max_length=20,verbose_name='Upload Method')

file_project/file_upload/forms.py
from django import forms
from .models import File


class FileUploadForm(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))
    upload_method = forms.CharField(label='Upload Method', max_length=20,
                                    widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_file(self):
        file = self.cleaned_data['file']
        ext = file.name.split('.')[-1].lower()
        if ext not in ['jpg', 'pdf', 'xlsx','png']:
            raise forms.ValidationError('Only jpq,pdf and xlsx files are allowed.')
        return file

class FileUploadModelForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('file','upload_method',)

        widgets = {
            'upload_method': forms.TextInput(attrs={'class': 'form-control'}),
            'file': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

        def clean_file(self):
            file = self.cleaned_data['file']
            ext = file.name.split('.')[-1].lower()
            if ext not in ['jpq','py','pdf']:
                raise forms.ValidationError('only jpq')
            return file

file_project/tasks/forms.py
from .models import Task
from django import forms

class TaskFrom(forms.ModelForm):

    class Meta:
        model = Task
        fields = '__all__'

file_project/file_download/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, StreamingHttpResponse, FileResponse
import os


# Create your views here.

def file_download(request, file_path):
    # do something...
    with open(file_path) as f:
        c = f.read()
    return HttpResponse(c)


def media_file_download(request, file_path):
    with open(file_path, 'rb') as f:
        try:
            response = HttpResponse(f)
            response['content_type'] = 'application/octet-stream'
            response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
            return response
        except Exception:
            raise Http404


def file_response_download1(request, file_path):
    try:
        response = FileResponse(open(file_path, 'rb'))
        response['content_type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
        return response
    except Exception:
        raise Http404


def file_response_download(request, file_path):
    print(file_path)
    ext = os.path.basename(file_path).split('.')[-1].lower()

    if ext not in ['py', 'db', 'sqlite3']:
        response = FileResponse(open(file_path, 'rb'))
        response['content_type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
        return response
    else:
        raise Http404

file_project/file_upload/views.py
from django.shortcuts import render, redirect
from .models import File
from .forms import FileUploadForm, FileUploadModelForm
import os
import uuid
from django.http import JsonResponse
from django.template.defaultfilters import filesizeformat


# Create your views here.

def file_upload(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            upload_method = form.cleaned_data.get('upload_method')
            raw_file = form.cleaned_data.get('file')
            new_file = File()
            new_file.file = handle_uploaded_file(raw_file)
            new_file.upload_method = upload_method
            new_file.save()
            return redirect('/file/')
    else:
        form = FileUploadForm()
    return render(request, 'file_upload/upload_form.html', {'form': form, 'heading': 'Upload files with Regular Form'})


def handle_uploaded_file(file):
    ext = file.name.split('.')[-1]
    file_name = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    file_path = os.path.join('files', file_name)
    absolute_file_path = os.path.join('media', 'files', file_name)

    directory = os.path.dirname(absolute_file_path)
    if not os.path.exists(directory):
        os.makedirs(directory)

    with open(absolute_file_path, 'wb+') as destination:
        for chunk in file.chunks():
            destination.write(chunk)
    return file_path


def model_form_upload(request):
    if request.method == 'POST':
        form = FileUploadModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/file/')
    else:
        form = FileUploadModelForm()
    return render(request, 'file_upload/upload_form.html', {'form': form, 'heading': 'Upload files with ModelForm', })


def ajax_form_upload(request):
    form = FileUploadModelForm()
    return render(request, 'file_upload/ajax_upload_form.html', {'form': form, 'heading': 'File Upload with ajax'})


def ajax_upload(request):
    if request.method == 'POST':
        # 1
        upload_method = request.POST.get('upload_method')
        raw_file = request.FILES.get('file')
        new_file = File()
        new_file.file = handle_uploaded_file(raw_file)
        new_file.upload_method = upload_method
        new_file.save()

        # 2
        form = FileUploadModelForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()

            files = File.objects.all().order_by('-id')
            data = []
            for file in files:
                data.append(
                    {'url': file.file.url,
                     "size": filesizeformat(file.file.size),
                     "upload_method": file.upload_method, }
                )
            return JsonResponse(data, safe=False)
        else:
            data = {'error_msg': 'only jpq,pdf and xlsx files are allowed'}
            return JsonResponse(data)
    return JsonResponse({'error_msg': 'only POST method accpeted'})


def file_list(request):
    files = File.objects.all().order_by('-id')
    return render(request, 'file_upload/file_list.html', {'files': files, })

file_project/file_upload/templates/file_upload/ajax_upload_form.html
{% extends "file_upload/base.html" %}

{% block content %}

    {% if heading %}
        <h3>{{ heading }}</h3>
    {% endif %}
    <form action="" method="post" enctype="multipart/form-data">
        <ul class="errorlist"></ul>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="button" class="btn btn-info form-control" value="submit" id="btn"/>
    </form>
    <table class="table table-striped" id="result">
    </table>
{% endblock content %}

{% block js %}
    <script src=" https://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
    <script>
var csrftoken = $.cookie('csrftoken');
function csrfSafeMethod(method) {
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$(document).ready(function(){
   $('#btn').click(function(e){
        e.preventDefault();
        // 构建FormData对象
        var form_data = new FormData();
        form_data.append('file', $('#id_file')[0].files[0]);
        form_data.append('upload_method', $('#id_upload_method').val());
        $.ajax({
        url: '/file/ajax_upload/',
        data: form_data,
        type: 'POST',
        dataType: 'json',
        // 告诉jQuery不要去处理发送的数据, 发送对象。
        processData : false,
        // 告诉jQuery不要去设置Content-Type请求头
        contentType : false,
        // 获取POST所需的csrftoken
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }},
        success: function (data) {
            if(data['error_msg']) {
                var content = '<li>Only jpg, pdf and xlsx files are allowed.</li>';
                $('ul.errorlist').html(content);
            }
            else
            {
            var content= '<thead><tr>' +
            '<th>Name and URL</th>' +
            '<th>Size</th>' +
            '<th>Upload Method</th>' +
            '</tr></thead><tbody>';

             $.each(data, function(i, item) {
                  content = content +
                  '<tr><td>' +
                  "<a href= ' " +
                  item['url'] +
                  " '> " +
                  item['url'] +
                  '</a></td><td>' +
                  item['size'] +
                  '</td><td>' +
                  item['upload_method'] +
                   '</td><tr>'
                });
             content = content + "</tbody>";
             $('#result').html(content);
             }
           },
        });
   });
 });
    </script>
{% endblock js %}

file_project/file_upload/templates/file_upload/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django File Upload and Download{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
<main class="container-fluid">
<div class="container">
 {% block content %} {% endblock %}

</div>
</main>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% block js %}
{% endblock js %}
</body>
</html>

file_project/file_upload/templates/file_upload/file_list.html
{% extends "file_upload/base.html" %}

{% block content %}
    <h3>File list</h3>
<p class="text-lowercase">
    <a href="{% url 'file_upload:file_upload' %}">file_upload</a> <br/>
    <a href="{% url 'file_upload:model_form_upload' %}">model_form_upload</a> <br/>
    <a href="{% url 'file_upload:ajax_form_upload' %}">ajax_form_upload</a> <br/>
    <a href="{% url 'file_upload:ajax_upload' %}">ajax_upload</a> <br/>
    <a href="{% url 'file_upload:file_list' %}">file_list</a> <br/>

</p>
    {% if files %}
        <table class="table table-striped">
            <tbody>
                <tr>
                    <td>Filename & URL</td>
                    <td>FilesizeL</td>
                    <td>Upload MethodL</td>
                </tr>
            {% for file in files %}
                <tr>
{#                    <td><a href="{% url 'file_download:file_download' file.file.url %}">{{ file.file.url }}</a></td>#}
                    <td><a href="{{ file.file.url }}">{{ file.file.url }}</a></td>
                    <td>{{ file.file.size|filesizeformat }}</td>
                    <td>{{ file.upload_method }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
     {% else %}
        <p>No file upload yet please click <a href="{% url 'file_upload:ajax_upload' %}">here</a>to upload files</p>
    {% endif %}
{% endblock content %}

file_project/file_upload/templates/file_upload/upload_form.html
{% extends "file_upload/base.html" %}

{% block content %}

    {% if heading %}
        <h3>{{ heading }}</h3>
    {% endif %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-info form-control" type="submit" value="submit">Upload</button>
    </form>

{% endblock content %}

file_project/tasks/templates/tasks/task_confirm_delete.html
<!DOCTYPE html>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ task }}"?</p>
    <input type="submit" value="Confirm" />
</form>

file_project/tasks/templates/tasks/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task Detail</title>
</head>
<body>
<p>
    Task Name: {{ task.name }} | <a href="{% url 'tasks:task_update' task.id %}">Update</a>
    <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>
</p>
<p>Task:Status: {{ task.get_status_display }}</p>
<p>
    <a href="{% url 'tasks:task_list' %}">View All tasks</a> |
    <a href="{% url 'tasks:task_create' %}">New Tasks</a>
</p>
</body>
</html>

file_project/tasks/templates/tasks/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if object %}Edit Task {% else %} Create New Task {% endif %}</title>
</head>
<body>
<h3>{% if object %}Edit Task {% else %} Create New Task {% endif %}</h3>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Submit" class="btn btn-success"></p>
</form>
</body>
</html>

file_project/tasks/templates/tasks/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task List</title>
</head>
<body>
<h3>Task List</h3>
{% for task in tasks %}
    <p>
        {{ forloop.counter }} . {{ task.name }} - {{ task.get_status_dispaly }}
        <a href="{% url 'tasks:task_update'  task.id %}">Update</a> |
        <a href="{% url 'tasks:task_delete'  task.id %}">Delete</a> |
        <a href="{% url 'tasks:task_create'   %}">create</a> |
        <a href="{% url 'tasks:task_detail'  task.id %}">detail</a> |
        )

    </p>
{% endfor %}
<p><a href="{% url 'tasks:task_create'  %}">Add a new task</a></p>
</body>
</html>